### ISSUE TITLE
Pin React-dash to React v.15.6.2

### ISSUE THREAD

**Issue by iris-i** [NuCivic/react-dash#69]
Pin the package.json for React & React-Dom to 15.6.2, to avoid new builds getting setup with v16.
Story: #68

**Comment by iris-i** [comment]
### Testing Steps:
Running through these steps should start up a working instance of react-dash
1. Brew install yarn. -- (Optional step if you don't have yarn installed)
2. git clone git@github.com:NuCivic/react-dash.git react-dash
3. cd react-dash
4. yarn install
5. yarn start

OR if you don't have homebrew or prefer to use npm: (this _should_ work too)
1. git clone git@github.com:NuCivic/react-dash.git react-dash
2. cd react-dash
3. npm install
4. npm start.

**Comment by JayDarnell** [comment]
@iris-i - here are my testing results:

`jay@jay-ThinkPad-P50:~/workspace$ git clone git@github.com:NuCivic/react-dash.git react-dash
Cloning into 'react-dash'...
remote: Counting objects: 5550, done.
remote: Compressing objects: 100% (24/24), done.
remote: Total 5550 (delta 15), reused 16 (delta 7), pack-reused 5519
Receiving objects: 100% (5550/5550), 11.52 MiB | 2.08 MiB/s, done.
Resolving deltas: 100% (3923/3923), done.
Checking connectivity... done.
jay@jay-ThinkPad-P50:~/workspace$ cd react-dash
jay@jay-ThinkPad-P50:~/workspace/react-dash(master)$ npm install
npm WARN peerDependencies The peer dependency react included from react-dash will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency react-dom included from react-dash will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
npm WARN engine react-hot-loader@3.0.0: wanted: {"node":">= 6"} (current: {"node":"4.8.4","npm":"2.15.11"})
npm WARN engine geojson@0.3.0: wanted: {"node":"0.10.x"} (current: {"node":"4.8.4","npm":"2.15.11"})
npm WARN peerDependencies The peer dependency react-dom@^15.4.2 included from react-addons-test-utils will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency react@^0.14.0 || ^15.0.0-0 included from react-responsive-accordion will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency react@^0.14.0 || ^15.0.0-0 included from react-collapsible will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency react@^0.14 || ^15.0.0-rc || ^15.0 included from react-input-autosize will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN peerDependencies The peer dependency react@^0.14 || ^15.0.0-rc || ^15.0 included from react-select will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency react-dom@^0.14 || ^15.0.0-rc || ^15.0 included from react-select will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN optional dep failed, continuing fsevents@1.1.2
npm WARN peerDependencies The peer dependency react@^0.14.0 || ^15.0.0 included from react-router will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN optional dep failed, continuing fsevents@1.1.2
 
> phantomjs-prebuilt@2.1.15 install /home/jay/workspace/react-dash/node_modules/karma-phantomjs-launcher/node_modules/phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-linux-x86_64.tar.bz2
Saving to /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
Receiving...
- [===================================-----] 87%/
Received 22866K total.
Extracting tar contents (via spawned process)
Removing /home/jay/workspace/react-dash/node_modules/karma-phantomjs-launcher/node_modules/phantomjs-prebuilt/lib/phantom
Copying extracted folder /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2-extract-1507668767957/phantomjs-2.1.1-linux-x86_64 -> /home/jay/workspace/react-dash/node_modules/karma-phantomjs-launcher/node_modules/phantomjs-prebuilt/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /home/jay/workspace/react-dash/node_modules/karma-phantomjs-launcher/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs
-
> node-sass@3.13.1 install /home/jay/workspace/react-dash/node_modules/node-sass
> node scripts/install.js

Cached binary found at /home/jay/.npm/node-sass/3.13.1/linux-x64-46_binding.node

> node-sass@3.13.1 postinstall /home/jay/workspace/react-dash/node_modules/node-sass
> node scripts/build.js

Binary found at /home/jay/workspace/react-dash/node_modules/node-sass/vendor/linux-x64-46/binding.node
Testing binary
Binary is fine
npm ERR! Linux 4.4.0-96-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.8.4
npm ERR! npm  v2.15.11
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react-dom@16.0.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer fixed-data-table-2@0.7.17 wants react-dom@>=0.14.0 || ^0.14.0-beta3
npm ERR! peerinvalid Peer react-nvd3@0.5.7 wants react-dom@>=0.14.0
npm ERR! peerinvalid Peer react-select@1.0.0-rc.1 wants react-dom@^0.14 || ^15.0.0-rc || ^15.0
npm ERR! peerinvalid Peer react-addons-test-utils@15.6.2 wants react-dom@^15.4.2

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jay/workspace/react-dash/npm-debug.log
`

**Comment by iris-i** [comment]
@JayDarnell ugh.. Apologies I just updated the testing steps to pull the code from the PR branch not the master branch. Pls try again, it should work now.

**Comment by JayDarnell** [comment]
@iris-i - do forgive my limited npm experience. I removed the react-dash folder created from the previous test and went through the testing steps again. Things look better this time but some dependencies still appear to have been missed.

`jay@jay-ThinkPad-P50:~/workspace$ git clone -b update-packages --single-branch git@github.com:NuCivic/react-dash.git react-dash
Cloning into 'react-dash'...
remote: Counting objects: 4902, done.
remote: Compressing objects: 100% (47/47), done.
remote: Total 4902 (delta 84), reused 103 (delta 77), pack-reused 4778
Receiving objects: 100% (4902/4902), 10.48 MiB | 6.45 MiB/s, done.
Resolving deltas: 100% (3436/3436), done.
Checking connectivity... done.
jay@jay-ThinkPad-P50:~/workspace$ cd react-dash
jay@jay-ThinkPad-P50:~/workspace/react-dash(update-packages)$ npm install
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
npm WARN engine geojson@0.3.0: wanted: {"node":"0.10.x"} (current: {"node":"4.8.4","npm":"2.15.11"})
npm WARN engine react-hot-loader@3.0.0: wanted: {"node":">= 6"} (current: {"node":"4.8.4","npm":"2.15.11"})
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN optional dep failed, continuing fsevents@1.1.2
npm WARN optional dep failed, continuing fsevents@1.1.2
 
> phantomjs-prebuilt@2.1.15 install /home/jay/workspace/react-dash/node_modules/karma-phantomjs-launcher/node_modules/phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Download already available at /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
Verified checksum of previously downloaded file
Extracting tar contents (via spawned process)
Removing /home/jay/workspace/react-dash/node_modules/karma-phantomjs-launcher/node_modules/phantomjs-prebuilt/lib/phantom
Copying extracted folder /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2-extract-1507676156055/phantomjs-2.1.1-linux-x86_64 -> /home/jay/workspace/react-dash/node_modules/karma-phantomjs-launcher/node_modules/phantomjs-prebuilt/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /home/jay/workspace/react-dash/node_modules/karma-phantomjs-launcher/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs
|
> node-sass@3.13.1 install /home/jay/workspace/react-dash/node_modules/node-sass
> node scripts/install.js

Cached binary found at /home/jay/.npm/node-sass/3.13.1/linux-x64-46_binding.node

> node-sass@3.13.1 postinstall /home/jay/workspace/react-dash/node_modules/node-sass
> node scripts/build.js

Binary found at /home/jay/workspace/react-dash/node_modules/node-sass/vendor/linux-x64-46/binding.node
Testing binary
Binary is fine
react-addons-test-utils@15.6.2 node_modules/react-addons-test-utils

fetch-polyfill@0.8.2 node_modules/fetch-polyfill

babel-plugin-transform-object-assign@6.22.0 node_modules/babel-plugin-transform-object-assign

json-loader@0.5.7 node_modules/json-loader

colorbrewer@1.0.0 node_modules/colorbrewer

karma-jasmine@0.3.8 node_modules/karma-jasmine

react-collapsible@1.5.0 node_modules/react-collapsible

react-responsive-accordion@1.0.0 node_modules/react-responsive-accordion

classnames@2.2.5 node_modules/classnames

dkan-es6-data-backend@0.0.1 node_modules/dkan-es6-data-backend

csv-es6-data-backend@0.0.1 node_modules/csv-es6-data-backend

geojson@0.3.0 node_modules/geojson

react-input-autosize@1.1.0 node_modules/react-input-autosize

karma-spec-reporter@0.0.20 node_modules/karma-spec-reporter
└── colors@0.6.2

file-loader@0.8.5 node_modules/file-loader
└── loader-utils@0.2.17 (object-assign@4.1.1, big.js@3.2.0, emojis-list@2.1.0, json5@0.5.1)

jasmine-core@2.8.0 node_modules/jasmine-core

sass-loader@3.2.3 node_modules/sass-loader
├── object-assign@4.1.1
├── async@1.5.2
└── loader-utils@0.2.17 (big.js@3.2.0, emojis-list@2.1.0, json5@0.5.1)

eslint-plugin-react@3.16.1 node_modules/eslint-plugin-react

style-loader@0.13.2 node_modules/style-loader
└── loader-utils@1.1.0 (big.js@3.2.0, emojis-list@2.1.0, json5@0.5.1)

d3-time-format@0.3.2 node_modules/d3-time-format
└── d3-time@0.2.6

extract-text-webpack-plugin@1.0.1 node_modules/extract-text-webpack-plugin
├── async@1.5.2
├── loader-utils@0.2.17 (object-assign@4.1.1, big.js@3.2.0, emojis-list@2.1.0, json5@0.5.1)
└── webpack-sources@0.1.5 (source-list-map@0.1.8, source-map@0.5.7)

react-select@1.0.0-rc.1 node_modules/react-select

babel-preset-react@6.24.1 node_modules/babel-preset-react
├── babel-plugin-syntax-jsx@6.18.0
├── babel-plugin-transform-react-jsx-self@6.22.0
├── babel-plugin-transform-react-display-name@6.25.0
├── babel-plugin-transform-react-jsx-source@6.22.0
├── babel-preset-flow@6.23.0 (babel-plugin-transform-flow-strip-types@6.22.0)
└── babel-plugin-transform-react-jsx@6.24.1 (babel-helper-builder-react-jsx@6.26.0)

babel-loader@6.4.1 node_modules/babel-loader
├── object-assign@4.1.1
├── loader-utils@0.2.17 (big.js@3.2.0, emojis-list@2.1.0, json5@0.5.1)
├── mkdirp@0.5.1 (minimist@0.0.8)
└── find-cache-dir@0.1.1 (commondir@1.0.1, pkg-dir@1.0.0)

babel-plugin-transform-class-properties@6.24.1 node_modules/babel-plugin-transform-class-properties
├── babel-plugin-syntax-class-properties@6.13.0
├── babel-template@6.26.0 (babylon@6.18.0, babel-types@6.26.0, babel-traverse@6.26.0)
└── babel-helper-function-name@6.24.1 (babel-helper-get-function-arity@6.24.1, babel-types@6.26.0, babel-traverse@6.26.0)

babel-preset-es2015@6.24.1 node_modules/babel-preset-es2015
├── babel-plugin-transform-es2015-spread@6.22.0
├── babel-plugin-transform-es2015-literals@6.22.0
├── babel-plugin-transform-es2015-for-of@6.23.0
├── babel-plugin-transform-es2015-template-literals@6.22.0
├── babel-plugin-transform-es2015-destructuring@6.23.0
├── babel-plugin-transform-es2015-arrow-functions@6.22.0
├── babel-plugin-check-es2015-constants@6.22.0
├── babel-plugin-transform-es2015-block-scoped-functions@6.22.0
├── babel-plugin-transform-es2015-typeof-symbol@6.23.0
├── babel-plugin-transform-es2015-sticky-regex@6.24.1 (babel-helper-regex@6.26.0, babel-types@6.26.0)
├── babel-plugin-transform-es2015-shorthand-properties@6.24.1 (babel-types@6.26.0)
├── babel-plugin-transform-es2015-duplicate-keys@6.24.1 (babel-types@6.26.0)
├── babel-plugin-transform-es2015-unicode-regex@6.24.1 (regexpu-core@2.0.0, babel-helper-regex@6.26.0)
├── babel-plugin-transform-regenerator@6.26.0 (regenerator-transform@0.10.1)
├── babel-plugin-transform-es2015-block-scoping@6.26.0 (babel-template@6.26.0, babel-types@6.26.0, babel-traverse@6.26.0)
├── babel-plugin-transform-es2015-classes@6.24.1 (babel-helper-replace-supers@6.24.1, babel-helper-optimise-call-expression@6.24.1, babel-messages@6.23.0, babel-helper-define-map@6.26.0, babel-helper-function-name@6.24.1, babel-template@6.26.0, babel-types@6.26.0, babel-traverse@6.26.0)
├── babel-plugin-transform-es2015-parameters@6.24.1 (babel-helper-get-function-arity@6.24.1, babel-helper-call-delegate@6.24.1, babel-template@6.26.0, babel-types@6.26.0, babel-traverse@6.26.0)
├── babel-plugin-transform-es2015-modules-amd@6.24.1 (babel-template@6.26.0)
├── babel-plugin-transform-es2015-computed-properties@6.24.1 (babel-template@6.26.0)
├── babel-plugin-transform-es2015-modules-umd@6.24.1 (babel-template@6.26.0)
├── babel-plugin-transform-es2015-object-super@6.24.1 (babel-helper-replace-supers@6.24.1)
├── babel-plugin-transform-es2015-function-name@6.24.1 (babel-types@6.26.0, babel-helper-function-name@6.24.1)
├── babel-plugin-transform-es2015-modules-systemjs@6.24.1 (babel-helper-hoist-variables@6.24.1, babel-template@6.26.0)
└── babel-plugin-transform-es2015-modules-commonjs@6.26.0 (babel-plugin-transform-strict-mode@6.24.1, babel-types@6.26.0, babel-template@6.26.0)

bootstrap@3.3.7 node_modules/bootstrap

babel-preset-stage-0@6.24.1 node_modules/babel-preset-stage-0
├── babel-plugin-transform-function-bind@6.22.0 (babel-plugin-syntax-function-bind@6.13.0)
├── babel-plugin-transform-do-expressions@6.22.0 (babel-plugin-syntax-do-expressions@6.13.0)
└── babel-preset-stage-1@6.24.1 (babel-plugin-transform-export-extensions@6.22.0, babel-plugin-transform-class-constructor-call@6.24.1, babel-preset-stage-2@6.24.1)

webpack-dev-server@1.16.5 node_modules/webpack-dev-server
├── open@0.0.5
├── connect-history-api-fallback@1.3.0
├── stream-cache@0.0.2
├── strip-ansi@3.0.1 (ansi-regex@2.1.1)
├── supports-color@3.2.3 (has-flag@1.0.0)
├── optimist@0.6.1 (wordwrap@0.0.3, minimist@0.0.10)
├── compression@1.7.1 (on-headers@1.0.1, vary@1.1.2, bytes@3.0.0, safe-buffer@5.1.1, compressible@2.0.11, debug@2.6.9, accepts@1.3.4)
├── webpack-dev-middleware@1.12.0 (path-is-absolute@1.0.1, time-stamp@2.0.0, range-parser@1.2.0, mime@1.4.1, memory-fs@0.4.1)
├── express@4.16.2 (escape-html@1.0.3, array-flatten@1.1.1, setprototypeof@1.1.0, cookie-signature@1.0.6, utils-merge@1.0.1, encodeurl@1.0.1, methods@1.1.2, merge-descriptors@1.0.1, content-type@1.0.4, serve-static@1.13.1, range-parser@1.2.0, vary@1.1.2, etag@1.8.1, path-to-regexp@0.1.7, content-disposition@0.5.2, parseurl@1.3.2, cookie@0.3.1, fresh@0.5.2, statuses@1.3.1, safe-buffer@5.1.1, depd@1.1.1, qs@6.5.1, on-finished@2.3.0, finalhandler@1.1.0, proxy-addr@2.0.2, debug@2.6.9, send@0.16.1, accepts@1.3.4, type-is@1.6.15, body-parser@1.18.2)
├── sockjs@0.3.18 (uuid@2.0.3, faye-websocket@0.10.0)
├── serve-index@1.9.1 (escape-html@1.0.3, parseurl@1.3.2, batch@0.6.1, mime-types@2.1.17, accepts@1.3.4, http-errors@1.6.2, debug@2.6.9)
├── http-proxy-middleware@0.17.4 (is-glob@3.1.0, http-proxy@1.16.2, micromatch@2.3.11)
└── sockjs-client@1.1.4 (inherits@2.0.3, json3@3.3.2, url-parse@1.1.9, debug@2.6.9, eventsource@0.1.6, faye-websocket@0.11.1)

react-router@2.8.1 node_modules/react-router
├── warning@3.0.0
├── invariant@2.2.2
├── hoist-non-react-statics@1.2.0
├── loose-envify@1.3.1 (js-tokens@3.0.2)
└── history@2.1.2 (warning@2.1.0, deep-equal@1.0.1, query-string@3.0.3)

react-nvd3@0.5.7 node_modules/react-nvd3
└── nvd3@1.8.6

d3@3.5.17 node_modules/d3

karma-phantomjs-launcher@1.0.4 node_modules/karma-phantomjs-launcher
└── phantomjs-prebuilt@2.1.15 (progress@1.1.8, kew@0.7.0, which@1.2.14, es6-promise@4.0.5, request-progress@2.0.1, hasha@2.2.0, fs-extra@1.0.0, extract-zip@1.6.5, request@2.81.0)

karma-coverage@0.4.2 node_modules/karma-coverage
├── minimatch@2.0.10 (brace-expansion@1.1.8)
├── source-map@0.4.4 (amdefine@1.0.1)
├── dateformat@1.0.12 (get-stdin@4.0.1, meow@3.7.0)
└── istanbul@0.3.22 (abbrev@1.0.9, async@1.5.2, wordwrap@1.0.0, nopt@3.0.6, esprima@2.5.0, once@1.4.0, supports-color@3.2.3, which@1.3.0, mkdirp@0.5.1, fileset@0.2.1, resolve@1.1.7, escodegen@1.7.1, js-yaml@3.10.0, handlebars@4.0.10)

karma-webpack@1.8.1 node_modules/karma-webpack
├── async@0.9.2
├── loader-utils@0.2.17 (object-assign@4.1.1, big.js@3.2.0, emojis-list@2.1.0, json5@0.5.1)
├── source-map@0.1.43 (amdefine@1.0.1)
├── webpack-dev-middleware@1.12.0 (time-stamp@2.0.0, path-is-absolute@1.0.1, range-parser@1.2.0, mime@1.4.1, memory-fs@0.4.1)
└── lodash@3.10.1

topojson@1.6.27 node_modules/topojson
├── d3-queue@2.0.3
├── rw@1.3.3
├── optimist@0.3.7 (wordwrap@0.0.3)
├── shapefile@0.3.1 (d3-queue@1.2.3, iconv-lite@0.2.11)
└── d3-geo-projection@0.2.16 (brfs@1.4.3)

webpack@1.15.0 node_modules/webpack
├── interpret@0.6.6
├── tapable@0.1.10
├── clone@1.0.2
├── async@1.5.2
├── supports-color@3.2.3 (has-flag@1.0.0)
├── loader-utils@0.2.17 (object-assign@4.1.1, big.js@3.2.0, emojis-list@2.1.0, json5@0.5.1)
├── enhanced-resolve@0.9.1 (graceful-fs@4.1.11, memory-fs@0.2.0)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── optimist@0.6.1 (wordwrap@0.0.3, minimist@0.0.10)
├── acorn@3.3.0
├── memory-fs@0.3.0 (errno@0.1.4, readable-stream@2.3.3)
├── webpack-core@0.6.9 (source-list-map@0.1.8, source-map@0.4.4)
├── uglify-js@2.7.5 (async@0.2.10, uglify-to-browserify@1.0.2, source-map@0.5.7, yargs@3.10.0)
├── watchpack@0.2.9 (graceful-fs@4.1.11, async@0.9.2, chokidar@1.7.0)
└── node-libs-browser@0.7.0 (https-browserify@0.0.1, tty-browserify@0.0.0, path-browserify@0.0.0, punycode@1.4.1, string_decoder@0.10.31, constants-browserify@1.0.0, os-browserify@0.2.1, process@0.11.10, assert@1.4.1, domain-browser@1.1.7, querystring-es3@0.2.1, timers-browserify@2.0.4, stream-browserify@2.0.1, events@1.1.1, vm-browserify@0.0.4, console-browserify@1.1.0, util@0.10.3, url@0.11.0, readable-stream@2.3.3, stream-http@2.7.2, buffer@4.9.1, browserify-zlib@0.1.4, crypto-browserify@3.3.0)

node-sass@3.13.1 node_modules/node-sass
├── get-stdin@4.0.1
├── lodash.assign@4.2.0
├── lodash.clonedeep@4.5.0
├── async-foreach@0.1.3
├── in-publish@2.0.0
├── chalk@1.1.3 (escape-string-regexp@1.0.5, supports-color@2.0.0, ansi-styles@2.2.1, has-ansi@2.0.0, strip-ansi@3.0.1)
├── nan@2.7.0
├── mkdirp@0.5.1 (minimist@0.0.8)
├── cross-spawn@3.0.1 (lru-cache@4.1.1, which@1.3.0)
├── glob@7.1.2 (path-is-absolute@1.0.1, inherits@2.0.3, fs.realpath@1.0.0, inflight@1.0.6, once@1.4.0, minimatch@3.0.4)
├── gaze@1.1.2 (globule@1.2.0)
├── npmlog@4.1.2 (set-blocking@2.0.0, console-control-strings@1.1.0, are-we-there-yet@1.1.4, gauge@2.7.4)
├── meow@3.7.0 (map-obj@1.0.1, decamelize@1.2.0, trim-newlines@1.0.0, object-assign@4.1.1, camelcase-keys@2.1.0, minimist@1.2.0, loud-rejection@1.6.0, normalize-package-data@2.4.0, redent@1.0.0, read-pkg-up@1.0.1)
├── sass-graph@2.2.4 (scss-tokenizer@0.2.3, yargs@7.1.0)
├── request@2.83.0 (aws-sign2@0.7.0, tunnel-agent@0.6.0, oauth-sign@0.8.2, forever-agent@0.6.1, caseless@0.12.0, is-typedarray@1.0.0, safe-buffer@5.1.1, stringstream@0.0.5, aws4@1.6.0, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.1, performance-now@2.1.0, uuid@3.1.0, qs@6.5.1, combined-stream@1.0.5, mime-types@2.1.17, tough-cookie@2.3.3, form-data@2.3.1, hawk@6.0.2, http-signature@1.2.0, har-validator@5.0.3)
└── node-gyp@3.6.2 (rimraf@2.6.2, graceful-fs@4.1.11, semver@5.3.0, osenv@0.1.4, which@1.3.0, nopt@3.0.6, fstream@1.0.11, minimatch@3.0.4, tar@2.2.1)

css-loader@0.23.1 node_modules/css-loader
├── object-assign@4.1.1
├── source-list-map@0.1.8
├── loader-utils@0.2.17 (big.js@3.2.0, emojis-list@2.1.0, json5@0.5.1)
├── css-selector-tokenizer@0.5.4 (fastparse@1.1.1, cssesc@0.1.0)
├── lodash.camelcase@3.0.1 (lodash._createcompounder@3.0.0)
├── postcss@5.2.18 (js-base64@2.3.2, supports-color@3.2.3, source-map@0.5.7, chalk@1.1.3)
├── postcss-modules-extract-imports@1.1.0 (postcss@6.0.13)
├── postcss-modules-scope@1.1.0 (css-selector-tokenizer@0.7.0, postcss@6.0.13)
├── postcss-modules-local-by-default@1.2.0 (css-selector-tokenizer@0.7.0, postcss@6.0.13)
├── postcss-modules-values@1.3.0 (icss-replace-symbols@1.1.0, postcss@6.0.13)
└── cssnano@3.10.0 (decamelize@1.2.0, postcss-normalize-charset@1.1.1, postcss-reduce-transforms@1.0.4, postcss-discard-empty@2.1.0, postcss-minify-gradients@1.0.5, postcss-discard-duplicates@2.1.0, postcss-merge-idents@2.1.7, postcss-reduce-initial@1.0.1, postcss-convert-values@2.6.1, postcss-discard-comments@2.0.4, defined@1.0.0, postcss-value-parser@3.3.0, postcss-minify-font-values@1.0.5, postcss-discard-overridden@0.1.1, postcss-reduce-idents@2.4.0, postcss-ordered-values@2.2.3, postcss-discard-unused@2.2.3, postcss-zindex@2.2.0, postcss-unique-selectors@2.0.2, postcss-minify-params@1.2.2, postcss-merge-longhand@2.0.2, has@1.0.1, postcss-filter-plugins@2.0.2, postcss-calc@5.3.1, postcss-normalize-url@3.0.8, postcss-minify-selectors@2.1.1, postcss-colormin@2.2.2, postcss-svgo@2.1.6, postcss-merge-rules@2.1.2, autoprefixer@6.7.7)

lodash@4.17.4 node_modules/lodash

flux@2.1.1 node_modules/flux
├── immutable@3.8.2
├── fbjs@0.1.0-alpha.7 (whatwg-fetch@0.9.0, promise@7.3.1, core-js@1.2.7)
└── fbemitter@2.1.1 (fbjs@0.8.16)

babel-eslint@4.1.8 node_modules/babel-eslint
├── acorn-to-esprima@1.0.7
├── lodash.assign@3.2.0 (lodash._baseassign@3.2.0, lodash._createassigner@3.1.1, lodash.keys@3.1.2)
├── lodash.pick@3.1.0 (lodash.restparam@3.6.1, lodash._bindcallback@3.0.1, lodash._pickbyarray@3.0.2, lodash._baseflatten@3.1.4, lodash._pickbycallback@3.0.0)
└── babel-core@5.8.38 (slash@1.0.0, try-resolve@1.0.1, babel-plugin-remove-console@1.0.1, babel-plugin-remove-debugger@1.0.1, babel-plugin-jscript@1.0.4, babel-plugin-inline-environment-variables@1.0.1, babel-plugin-dead-code-elimination@1.0.2, babel-plugin-property-literals@1.0.1, babel-plugin-react-constant-elements@1.0.3, babel-plugin-react-display-name@1.0.3, babel-plugin-eval@1.0.1, babel-plugin-constant-folding@1.0.1, path-exists@1.0.0, shebang-regex@1.0.0, trim-right@1.0.1, to-fast-properties@1.0.3, babel-plugin-member-expression-literals@1.0.1, babel-plugin-undefined-to-void@1.1.6, fs-readdir-recursive@0.1.2, path-is-absolute@1.0.1, private@0.1.7, babel-plugin-proto-to-assign@1.0.4, babel-plugin-runtime@1.0.7, globals@6.4.1, esutils@2.0.2, convert-source-map@1.5.0, js-tokens@1.0.1, home-or-tmp@1.0.0, babel-plugin-undeclared-variables-check@1.0.2, babylon@5.8.38, source-map@0.5.7, debug@2.6.9, chalk@1.1.3, is-integer@1.0.7, repeating@1.1.3, detect-indent@3.0.1, minimatch@2.0.10, bluebird@2.11.0, output-file-sync@1.1.2, regexpu@1.3.0, source-map-support@0.2.10, resolve@1.4.0, json5@0.4.0, regenerator@0.8.40, lodash@3.10.1, core-js@1.2.7)

react@15.6.2 node_modules/react
├── object-assign@4.1.1
├── create-react-class@15.6.2
├── prop-types@15.6.0
├── loose-envify@1.3.1 (js-tokens@3.0.2)
└── fbjs@0.8.16 (setimmediate@1.0.5, ua-parser-js@0.7.14, promise@7.3.1, isomorphic-fetch@2.2.1, core-js@1.2.7)

react-hot-loader@3.0.0 node_modules/react-hot-loader
├── react-deep-force-update@2.1.1
├── react-proxy@3.0.0-alpha.1
├── source-map@0.6.1
├── global@4.3.2 (process@0.5.2, min-document@2.19.0)
├── babel-template@6.26.0 (babylon@6.18.0, babel-types@6.26.0, babel-traverse@6.26.0)
└── redbox-react@1.5.0 (object-assign@4.1.1, error-stack-parser@1.3.6, sourcemapped-stacktrace@1.1.7, prop-types@15.6.0)

fixed-data-table@0.6.4 node_modules/fixed-data-table
└── prop-types@15.6.0 (object-assign@4.1.1, loose-envify@1.3.1, fbjs@0.8.16)

fixed-data-table-2@0.7.17 node_modules/fixed-data-table-2
├── create-react-class@15.6.2 (object-assign@4.1.1, loose-envify@1.3.1, fbjs@0.8.16)
└── prop-types@15.6.0 (object-assign@4.1.1, loose-envify@1.3.1, fbjs@0.8.16)

react-dom@15.6.2 node_modules/react-dom
├── object-assign@4.1.1
├── prop-types@15.6.0
├── loose-envify@1.3.1 (js-tokens@3.0.2)
└── fbjs@0.8.16 (setimmediate@1.0.5, ua-parser-js@0.7.14, promise@7.3.1, isomorphic-fetch@2.2.1, core-js@1.2.7)

babel-polyfill@6.26.0 node_modules/babel-polyfill
├── regenerator-runtime@0.10.5
└── core-js@2.5.1

babel-core@6.26.0 node_modules/babel-core
├── slash@1.0.0
├── babel-messages@6.23.0
├── path-is-absolute@1.0.1
├── private@0.1.7
├── babel-helpers@6.24.1
├── babel-template@6.26.0
├── json5@0.5.1
├── babylon@6.18.0
├── convert-source-map@1.5.0
├── source-map@0.5.7
├── debug@2.6.9 (ms@2.0.0)
├── minimatch@3.0.4 (brace-expansion@1.1.8)
├── babel-types@6.26.0 (to-fast-properties@1.0.3, esutils@2.0.2)
├── babel-code-frame@6.26.0 (js-tokens@3.0.2, esutils@2.0.2, chalk@1.1.3)
├── babel-traverse@6.26.0 (globals@9.18.0, invariant@2.2.2)
├── babel-generator@6.26.0 (trim-right@1.0.1, jsesc@1.3.0, detect-indent@4.0.0)
└── babel-register@6.26.0 (source-map-support@0.4.18, home-or-tmp@2.0.0, mkdirp@0.5.1, core-js@2.5.1)

karma@0.13.22 node_modules/karma
├── isbinaryfile@3.0.2
├── rimraf@2.6.2
├── batch@0.5.3
├── graceful-fs@4.1.11
├── di@0.0.1
├── mime@1.4.1
├── colors@1.1.2
├── http-proxy@1.16.2 (eventemitter3@1.2.0, requires-port@1.0.0)
├── source-map@0.5.7
├── dom-serialize@2.2.1 (void-elements@2.0.1, custom-event@1.0.1, extend@3.0.1, ent@2.2.0)
├── minimatch@3.0.4 (brace-expansion@1.1.8)
├── glob@7.1.2 (path-is-absolute@1.0.1, inherits@2.0.3, fs.realpath@1.0.0, once@1.4.0, inflight@1.0.6)
├── useragent@2.2.1 (lru-cache@2.2.4, tmp@0.0.33)
├── bluebird@2.11.0
├── connect@3.6.5 (utils-merge@1.0.1, parseurl@1.3.2, debug@2.6.9, finalhandler@1.0.6)
├── optimist@0.6.1 (wordwrap@0.0.3, minimist@0.0.10)
├── body-parser@1.18.2 (content-type@1.0.4, bytes@3.0.0, depd@1.1.1, qs@6.5.1, on-finished@2.3.0, raw-body@2.3.2, http-errors@1.6.2, debug@2.6.9, iconv-lite@0.4.19, type-is@1.6.15)
├── expand-braces@0.1.2 (array-unique@0.2.1, array-slice@0.2.3, braces@0.1.5)
├── socket.io@1.7.4 (object-assign@4.1.0, socket.io-adapter@0.5.0, has-binary@0.1.7, debug@2.3.3, socket.io-parser@2.3.1, engine.io@1.8.4, socket.io-client@1.7.4)
├── log4js@0.6.38 (semver@4.3.6, readable-stream@1.0.34)
├── chokidar@1.7.0 (path-is-absolute@1.0.1, async-each@1.0.1, inherits@2.0.3, glob-parent@2.0.0, is-glob@2.0.1, is-binary-path@1.0.1, readdirp@2.1.0, anymatch@1.3.2)
├── lodash@3.10.1
└── core-js@2.5.1

babel-runtime@6.26.0 node_modules/babel-runtime
├── regenerator-runtime@0.11.0
└── core-js@2.5.1
jay@jay-ThinkPad-P50:~/workspace/react-dash(update-packages)$ npm start

> react-dash@0.6.1-4.2 start /home/jay/workspace/react-dash
> bash scripts/start.sh

ENV undefined
INDEX PATH ./examples/index.js
module.js:327
    throw err;
    ^

Error: Cannot find module 'minimist'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/jay/workspace/react-dash/server.js:5:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)

npm ERR! Linux 4.4.0-96-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.8.4
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE
npm ERR! react-dash@0.6.1-4.2 start: `bash scripts/start.sh`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-dash@0.6.1-4.2 start script 'bash scripts/start.sh'.
npm ERR! This is most likely a problem with the react-dash package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bash scripts/start.sh
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-dash
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls react-dash
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jay/workspace/react-dash/npm-debug.log
`
